version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: on-failure
    image: node-mysql-app
    env_file: ./.env
    ports:
      - $NODEJS_LOCAL_PORT:$NODEJS_DOCKER_PORT
    volumes: 
      - ./app:/app
      - app/node_modules
    depends_on:
      - mysqldb

volumes: 
  db-config:
  db-data: